### 1. Criar a conta do Gustavo
POST http://localhost:8080/contas
Content-Type: application/json

{
  "cpf": "11122233344",
  "titular": "Gustavo",
  "saldo": 500.00
}

### 2. Criar a conta da Maria
POST http://localhost:8080/contas
Content-Type: application/json

{
  "cpf": "99988877766",
  "titular": "Maria",
  "saldo": 300.00
}

### 3. Listar TODAS as contas
GET http://localhost:8080/contas

### 4. Buscar APENAS a conta do Gustavo pelo CPF
GET http://localhost:8080/contas/11122233344

### 5. Fazer um PIX do Gustavo para a Maria
POST http://localhost:8080/contas/transferencia
Content-Type: application/json

{
  "cpfOrigem": "11122233344",
  "cpfDestino": "99988877766",
  "valor": 100.00
}